### ISSUE TITLE
"pdf2svg" functionality?

### ISSUE THREAD

**Issue by twardoch** [CaSchmidt/cslabs#1]
@CaSchmidt Does your code contain any functionality that would allow to render a PDF into a series of QPainter calls, or, ultimately, an SVG graphic? I’m not a C++ developer myself, but I can see some bits in your code that look promising.

**Comment by CaSchmidt** [comment]
I am afraid that such functionality is neither planned nor possible. As of now csPDFium just renders a QImage of the page.
The QPainter features you probably saw are for extraction of the page's path objects, e.g. in a CAD drawing, and rely on a heavily patched version of PDFium.
Maybe MuPDF provides what you are looking for (https://www.mupdf.com/)?

**Comment by twardoch** [comment]
Thanks. The licensing model of MuPDF doesn't allow me to use it at this point, but I'll keep looking!
